---
abstract: 'a test module to test/assert response times'
author:
  - 'Jonas B. Nielsen <jonasbn@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.30'
  Test::Exception: '0'
  Test::More: '0'
  Test::Tester: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Timer
requires:
  Benchmark: '0'
  Carp: '0'
  English: '0'
  Error: '0'
  Test::Builder: '0'
  Test::Builder::Module: '0'
  perl: '5.012'
resources:
  bugtracker: https://github.com/jonasbn/testt/issues
  repository: git://github.com/jonasbn/testt.git
version: '0.10'
