---
abstract: 'test module to test/assert response times'
author:
  - 'Jonas B. Nielsen <jonasbn@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.30'
  Pod::Coverage::TrustPod: '0'
  Test::Fatal: '0'
  Test::Kwalitee: '1.21'
  Test::More: '0'
  Test::Pod: '1.41'
  Test::Pod::Coverage: '1.08'
  Test::Tester: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
  Module::Build: '0.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.009, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Timer
provides:
  Test::Timer:
    file: lib/Test/Timer.pm
    version: '1.00'
  Test::Timer::TimeoutException:
    file: lib/Test/Timer/TimeoutException.pm
    version: '1.00'
requires:
  Benchmark: '0'
  Carp: '0'
  English: '0'
  Error: '0'
  Test::Builder: '0'
  Test::Builder::Module: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/jonasbn/perl-test-timer/issues
  homepage: https://jonasbn.github.io/perl-test-timer/
  repository: https://github.com/jonasbn/perl-test-timer.git
version: '1.00'
x_serialization_backend: 'YAML::Tiny version 1.70'
